### ISSUE TITLE
Host resolving to multiple A records is constantly reordered

### ISSUE THREAD

**Issue by tenstad** [nais/fqdn-policy#83]
https://github.com/nais/fqdn-policy/blob/fcbf9432a7c800d5113ddde28f212be438f92177/controllers/fqdnnetworkpolicy_controller.go#L453-L475

The list should maybe be sorted, to avoid updating the resource on every reconcile?

```yaml
egress:
    - ports:
        - protocol: TCP
          port: 443
      to:
        - ipBlock:
            cidr: 8.8.8.16/32
        - ipBlock:
            cidr: 8.8.8.15/32
        - ipBlock:
            cidr: 8.8.8.11/32
        - ipBlock:
            cidr: 8.8.8.10/32
        - ipBlock:
            cidr: 8.8.8.9/32
        - ipBlock:
            cidr: 8.8.8.13/32
        - ipBlock:
            cidr: 8.8.8.14/32
        - ipBlock:
            cidr: 8.8.8.17/32
        - ipBlock:
            cidr: 8.8.8.8/32
```
